project:
  type: manuscript       

manuscript:
  article: index.qmd      

bibliography: references.bib

format:
  plos-pdf: default
  html:
    theme: cosmo
    toc: true
  docx: default

execute:
  freeze: auto
  echo: false
  warning: false